### ISSUE TITLE
Error when trying to skip authorization for given controllers in Rails 5

### ISSUE THREAD

**Issue by onkeld** [AnalyticsMediaGroup/strongbolt#25]
I'm trying to set up strongbolt with devise in a fresh rails 5 app according to the minimal example application.
Everything runs fine until the point where I want to exclude the devise controllers from authorization.

I added the line 
`config.skip_controller_authorization_for` "Devise::Sessions", "Devise::Registrations"`
to the initializer.
When restartung the server, it throws the following error:

> /gems/activesupport-5.0.1.rc1/lib/active_support/callbacks.rb:641:in `block (2 levels) in skip_callback': Before process_action callback :check_authorization has not been defined (ArgumentError)

Sounds rather strange that a callback called 
  >:check_authorization

should be needed if I actually want to skip authorization...

Any suggestions?

**Comment by onkeld** [comment]
If I comment out the config.skip... line, everything starts up fine, but then I can't log out my devise user anymore since the Devise::Sessions controller needs a current user which is authorized to run it...

**Comment by tobithiel** [comment]
Sorry about that, we're still on Rails 4. The cause is this particular PR: rails/rails#19029 which makes `skip_before_action` throw an error if the particular action doesn't exist anymore.

`check_authorization` is added to every controller by default, so that each action will be checked by default. Since the removing via `skip_...` failed, your error message still includes `check_authorization`

Please try the latest master branch. I've committed a fix for this particular issue and the example seems to work fine with that on Rails 5.

**Comment by onkeld** [comment]
Just to follow up: seems to work with master.
However, I found another quirk there in my setup:

The controller I want to skip authorization on is a model-less controller. 
After switching to master branch for the gem, I'm not getting above error anymore, but strongbolt instead complains about not knowing the model to authorize against.
Easily fixed by adding self.model_for_authorization = "User" to the controller, but isn't it stupid to even check for this if authorization is supposed to be skipped altogether?

Once again: Works for me now.

**Comment by onkeld** [comment]
Also, for the Devise controllers, I'm getting a new error now:

activesupport-5.0.1.rc2/lib/active_support/callbacks.rb:641:in `block (2 levels) in skip_callback': Before process_action callback :check_authorization has not been defined (ArgumentError)

The error happens when restarting the application.
Commenting out the strongbolt initializer line for skipping authorization, then starting the server and afterwards removing the comment again makes the app start.
Afterwards, when trying to log out my active user with devise, I get

Strongbolt::ModelNotFound in Devise::SessionsController#destroy
Model for controller sessions wasn't found

Seems like I'm missing something else there...

**Comment by onkeld** [comment]
Same happens for the registrations controller edit action.
My strongbolt.rb initializer has the line
   `config.skip_controller_authorization_for "Devise::Sessions", "Devise::Registrations"`
to skip auth on the Devise Controllers.
Apparently I still need some model though...

**Comment by onkeld** [comment]
Actually, the same error occurs, no matter the state of my initializer. 
If I comment out the    `config.skip_controller_authorization_for "Devise::Sessions", "Devise::Registrations"` line, I still get the same error asking for the model.

**Comment by onkeld** [comment]
So to summarize:

If I don't skip authorization for Devise::Sessions and Devise::Registrations in the initializer, my app starts, but I get the `ModelNotFound` Error. If I do skip authorization for the Devise controllers via the initializer, I can't start my App anymore raising the `activesupport-5.0.1.rc2/lib/active_support/callbacks.rb:641:in `block (2 levels) in skip_callback': Before process_action callback :check_authorization has not been defined (ArgumentError)` Error.

Any ideas about that?

**Comment by tobithiel** [comment]
You're writing that your getting a new error, but it's the exact same error message about the `:check_authorization` action just on a different controller, as far as I can tell. Am I missing something?
Anyways, skipping authorization for Devise Controllers works fine on our example app for us: https://github.com/AnalyticsMediaGroup/strongbolt_example. So please take a look at that and compare it.

That it complains about the missing model when authorization is skipped, is kind of awkward and unexpected. I agree with that. Can you please open a separate issue for that?

**Comment by onkeld** [comment]
New issue is opened under  #28.
No clue why the same error as before appeared on a different controller. When I restarted today, everything was working fine except for the new issue...

**Comment by tobithiel** [comment]
You will need to restart Rails servers etc if you modify an initializer. If not that can cause confusions like this.

**Comment by onkeld** [comment]
I knew about the restarting bit, but for some reasons, even after shutting down everything I knew of, some rails processes were still hanging in there. Must have shot them off to be orphaned at some point...
After a fresh restart of the PC these processes were gone and my initializer was being properly loaded...

Thanks again for the quick help!
